SHOW TABLES;
ALTER TABLE CLIENTES_NEPTUNO
MODIFY IDCliente VARCHAR(5) PRIMARY KEY,
MODIFY NombreCompania VARCHAR(100) NOT NULL,
MODIFY Pais VARCHAR(15) NOT NULL;
DESC CLIENTES_NEPTUNO;
RENAME TABLE clientes TO CONTACTOS;
ALTER TABLE clientes
MODIFY Cod_Cliente VARCHAR(7) PRIMARY KEY,
MODIFY Empresa VARCHAR(100) NOT NULL,
MODIFY Ciudad VARCHAR(25) NOT NULL,
MODIFY Telefono INT UNSIGNED,
MODIFY Responsable VARCHAR(30);
DESC CLIENTES;
ALTER TABLE PEDIDOS
MODIFY Numero_Pedido INT UNSIGNED PRIMARY KEY,
MODIFY Codigo_Cliente VARCHAR(7) NOT NULL,
MODIFY Fecha_Pedido DATE NOT NULL,
MODIFY Forma_Pago ENUM ('APLAZADO', 'CONTADO', 'TARJETA'),
MODIFY Enviado ENUM ('SI', 'NO');
DESC PEDIDOS;
ALTER TABLE PRODUCTOS
MODIFY Cod_Producto INT UNSIGNED PRIMARY KEY,
MODIFY Seccion VARCHAR(20) NOT NULL,
MODIFY Nombre VARCHAR(40) NOT NULL,
MODIFY Importado ENUM ('VERDADERO', 'FALSO') NOT NULL,
MODIFY Origen VARCHAR(25) NOT NULL,
MODIFY Dia INT UNSIGNED NOT NULL,
MODIFY Mes INT UNSIGNED NOT NULL,
MODIFY Ano INT UNSIGNED NOT NULL;
DESC PRODUCTOS;



