SHOW TABLES;
SELECT * FROM CLIENTES_NEPTUNO;
SELECT IDCLIENTE, NOMBRECOMPANIA, CONCAT(DIRECCION, ' - ', CIUDAD, ' - ', PAIS) UBICACION
FROM CLIENTES_NEPTUNO;
SELECT IDCLIENTE, NOMBRECOMPANIA, CONCAT_WS(' / ', DIRECCION, CIUDAD, PAIS) UBICACION
FROM CLIENTES_NEPTUNO;
SELECT IDCLIENTE, UPPER(NOMBRECOMPANIA) EMPRESA, CONCAT_WS(' / ', DIRECCION, CIUDAD, PAIS) UBICACION
FROM CLIENTES_NEPTUNO;
SELECT LOWER(IDCLIENTE) CODIGO, 
UPPER(NOMBRECOMPANIA) EMPRESA, CONCAT_WS(' / ', DIRECCION, CIUDAD, PAIS) UBICACION
FROM CLIENTES_NEPTUNO;
SELECT *, UPPER(CONCAT(LEFT(CIUDAD, 1), LEFT(PAIS,1), RIGHT(PAIS,2))) CODIGO
FROM CLIENTES_NEPTUNO;
SELECT * FROM NACIMIENTOS;
SELECT FECHA, LEFT(SEXO,1) SEXO, LEFT(TIPO_PARTO, 1) TIPO
FROM NACIMIENTOS;
SELECT SEXO, FECHA, TIPO_PARTO, ATENC_PART, LOCAL_PART, SUBSTRING(FECHA, 4, 2) MES
FROM NACIMIENTOS ORDER BY MES;
SELECT SEXO, FECHA, TIPO_PARTO, REPLACE(NACIONALIDAD, 'Chilena', 'Ciudadana') NACIONALIDAD
FROM NACIMIENTOS;

